version: "2.3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=002
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /var/data/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=002
      - VIRTUAL_PORT=7878
    volumes:
      - ./radarr/config:/config
      - /mnt/drvideo/film:/movies
      - /var/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=002
      - VIRTUAL_PORT=8989
    volumes:
      - ./sonarr/config:/config
      - /mnt/drvideo/series:/tv
      - /var/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=002
    volumes:
      - ./bazarr/config:/config
      - /mnt/drvideo/film:/movies
      - /mnt/drvideo/series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./jackett/config:/config
      - /var/data/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3579"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - BASE_URL=/ombi
    volumes:
      - ./ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
